# Generated by Django 4.2.4 on 2023-10-09 18:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdate',
            name='id',
        ),
        migrations.AddField(
            model_name='eventdate',
            name='event_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(default=uuid.uuid4, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
