# Generated by Django 4.2.4 on 2023-10-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_eventdate_id_eventdate_event_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventdate',
            unique_together={('event_id', 'date')},
        ),
    ]
