# Generated by Django 4.2.4 on 2023-09-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_event_date_delete_eventdates'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDates',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.ManyToManyField(to='base.eventdates'),
        ),
    ]
