# Generated by Django 4.2.4 on 2023-09-07 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_eventdates_remove_event_date_event_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventDates',
            new_name='EventDate',
        ),
    ]
