# Generated by Django 4.2.4 on 2023-10-09 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_vote_vote_unique_event_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.event')),
                ('notification', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_event_id_user',
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('event_id', 'username'), name='unique_vote'),
        ),
        migrations.AddField(
            model_name='notification',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
        migrations.AddField(
            model_name='availability',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.event'),
        ),
        migrations.AddField(
            model_name='availability',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('event_id', 'username')},
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(fields=('event_id', 'username'), name='unique_availability'),
        ),
    ]
