# Generated by Django 4.2.4 on 2023-10-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_availability_notification_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='availability',
            name='unique_availability',
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(fields=('event_id', 'username', 'date'), name='unique_availability'),
        ),
    ]
