# Generated by Django 4.2.7 on 2023-12-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_vote_unique_vote_vote_unique_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='voting',
            field=models.CharField(default='no', max_length=3),
        ),
    ]
