# Generated by Django 4.2.4 on 2023-10-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_availability_unique_availability_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('event_id', 'username', 'notification')},
        ),
    ]
