# Generated by Django 4.2.4 on 2023-10-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_notification_id_alter_notification_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
