# Generated by Django 4.2.4 on 2023-10-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_userevent_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userevent',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userevent',
            constraint=models.UniqueConstraint(fields=('event_id', 'username'), name='unique_userevent'),
        ),
    ]
