# Generated by Django 4.2.4 on 2023-10-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_userevent_id_alter_userevent_event_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eventdate',
            constraint=models.UniqueConstraint(fields=('event_id', 'date'), name='unique_event_date'),
        ),
    ]
