# Generated by Django 4.2.4 on 2023-10-18 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_eventdate_id_alter_eventdate_event_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserEvent',
            new_name='EventUser',
        ),
    ]
